name: CI
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # rebase and rebuild daily
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Get zlib
      working-directory: ${{ github.workspace }}\..
      run: git clone https://github.com/madler/zlib.git
    - name: Get curl
      working-directory: ${{ github.workspace }}\..
      run: git clone https://github.com/curl/curl.git
    - name: Get Gettext
      working-directory: ${{ github.workspace }}\..
      run: git clone https://github.com/ChristopherHX/gettext-msvc.git
    - name: Build
      working-directory: ${{ github.workspace }}\contrib\msbuild\
      run: powershell -Command "&'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' /p:Configuration=Release /p:Platform=x64 /p:VersionsCode=$(git describe --abbrev=0) /p:CURLDIR=${{ github.workspace }}\..\curl /p:ZLIBDIR=${{ github.workspace }}\..\zlib /p:GETTEXTDIR=${{ github.workspace }}\..\gettext-msvc\gettext-0.19.8 /p:LIBICONVDIR=${{ github.workspace }}\..\gettext-msvc\libiconv-1.16"
    - uses: actions/upload-artifact@master
      with:
        name: Git(nano)
        path: ${{ github.workspace }}/contrib/msbuild/bin